apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: node-sample-app
  app.kubernetes.io/instance: node-sample-app-instance
  app.kubernetes.io/name: node-sample-app
